repos:
  - repo: local
    hooks:
      - id: generate-docs
        name: Generate API docs
        language: system
        entry: pipenv run python utils/correct_pdoc_issues.py
        pass_filenames: false
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.11
    hooks:
      - id: pymarkdown
        pass_filenames: false
        args:
          - --config
          - clean.json
          - scan
          - .
          - ./docs
  - repo: local
    hooks:
      - id: verify-install-requirements
        name: Verify Install Requirements Match
        language: system
        entry: pipenv run python utils/verify_install_requirements.py
        pass_filenames: false
