name: Main

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight

jobs:
  scenario-tests:
    strategy:
      matrix:
        #python: [3.8, 3.9]
        #platform: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.8]
        platform: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@master
    - name: Setup Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install PipEnv
      uses: dschep/install-pipenv-action@v1
    - name: Sync With Repository
      run: pipenv sync
    - name: Execute Tests
      run: pipenv run pytest - k test_markdown_with_enabled_by_configuration_id
    - name: Report Coverage
      uses: codecov/codecov-action@v1
      if: github.event_name != 'schedule'
      with:
        file: ./report/coverage.xml
        name: ${{ matrix.python }} - ${{ matrix.platform }}
        fail_ci_if_error: true
  lint:
    strategy:
      matrix:
        python: [3.8]
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@master
    - name: Setup Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install PipEnv
      uses: dschep/install-pipenv-action@v1
    - name: Sync With Repository
      run: pipenv sync
    - name: Execute Flake8
      run: pipenv run flake8 --exclude dist,build
    - name: Execute PyLint on Source
      run: pipenv run pylint --rcfile=setup.cfg ./pymarkdown ./pymarkdown/extensions ./pymarkdown/plugins
    - name: Execute PyLint on Tests
      run: pipenv run pylint --rcfile=setup.cfg ./test
